Add Sprig Templating
redhat-cop/operator-utils pull request #34
Opened 2020-08-11 14:53 UTC by cnuland

I'm recommending this approach for adding Sprig templates because of the following reasons,

- It's a very simply implementation that prevents splitting functionality into different function calls
- omitempty will default the `EnableSprigTemplates` to false if no value is provided
- A consumer will need to explicitly enable the functionality, which would presume some knowledge of Sprig prior

I did the following tests using the namespace config operator,

1) Sprig test
I created a `GroupConfig` that takes the name of the group, lowers the cases of all characters, then shuffles. This was successful.
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupConfig
metadata:
  name: team-onboarding
spec:
  labelSelector:
    matchLabels:
      type: devproject    
  templates:
  - enableSprigTemplates: true
    objectTemplate: |
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: {{ .Name | lower | shuffle }}
```

2) go template route
I made sure the normal go templating path worked still by omitting the `EnableSprigTemplates` property. This was successful.

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupConfig
metadata:
  name: team-onboarding
spec:
  labelSelector:
    matchLabels:
      type: devproject    
  templates:
  - objectTemplate: |
      - apiVersion: v1
        kind: Namespace
        metadata:
          name:s {{ .Name }}
```

2020-08-13 11:19 UTC, raffaelespazzoli commented on pkg/util/lockedresourcecontroller/lockedresource/locked-resource.go
> +			tmpl = template.Must(template.New(resource.ObjectTemplate).Funcs(sprig.TxtFuncMap()).Parse(resource.ObjectTemplate))
with `must` I think the program will abort if there is an error, which should not happen

2020-08-13 11:21 UTC, raffaelespazzoli commented on pkg/util/apis/locked-resource.go
> +	EnableSprigTemplates bool `json:"enableSprigTemplates,omitempty"`
let's call this EnableAdvancedTemplateFunctions

2020-08-13 11:25 UTC, raffaelespazzoli commented on pkg/util/lockedresourcecontroller/lockedresource/locked-resource.go
> +			tmpl = template.Must(template.New(resource.ObjectTemplate).Funcs(sprig.TxtFuncMap()).Parse(resource.ObjectTemplate))
I'd like to add the same functions as helm does, see here:
https://github.com/helm/helm/blob/master/pkg/engine/funcs.go
basically it's the sprig function plus these utilities:
```
		"toToml":        toTOML,
		"toYaml":        toYAML,
		"fromYaml":      fromYAML,
		"fromYamlArray": fromYAMLArray,
		"toJson":        toJSON,
		"fromJson":      fromJSON,
		"fromJsonArray": fromJSONArray,
```
plus the lookup function. finally they remove a couple of function from sprig as they could be used for privilege escalation attack: 
```
	delete(f, "env")
	delete(f, "expandenv")
```

2020-08-13 11:26 UTC, raffaelespazzoli commented on pkg/util/lockedresourcecontroller/lockedresource/locked-resource.go
>  	tmpl, ok := templates[resource.ObjectTemplate]
we need to make this change also when constructing the template for the patches.

2020-09-08 03:21 UTC, cnuland commented on pkg/util/lockedresourcecontroller/lockedresource/locked-resource.go
> +			tmpl = template.Must(template.New(resource.ObjectTemplate).Funcs(sprig.TxtFuncMap()).Parse(resource.ObjectTemplate))
Completed, the only function I did not add was lookup. I was having trouble understanding how it was enabled with helm and also had trouble testing. If critical let me know and I can create a separate task to make it.

2020-09-08 03:21 UTC, cnuland commented on pkg/util/apis/locked-resource.go
> +	EnableSprigTemplates bool `json:"enableSprigTemplates,omitempty"`
done

2020-09-08 03:21 UTC, cnuland commented on pkg/util/lockedresourcecontroller/lockedresource/locked-resource.go
> +			tmpl = template.Must(template.New(resource.ObjectTemplate).Funcs(sprig.TxtFuncMap()).Parse(resource.ObjectTemplate))
done

2020-09-08 03:32 UTC, cnuland commented on pkg/util/lockedresourcecontroller/lockedresource/locked-resource.go
>  	tmpl, ok := templates[resource.ObjectTemplate]
I enabled the advanced templating for patching, I'm making an assumption since its using the same templating engine that the functionality is one to one and does not need to be tested beyond enabling it. If you'd like to test the above tests with the patch operator, or need me to, let me know.

2020-09-08 12:59 UTC, raffaelespazzoli requested changes

2020-09-08 12:59 UTC, raffaelespazzoli commented on pkg/util/apis/locked-resource.go
> +	EnableAdvancedTemplateFunctions bool `json:"enableAdvancedTemplateFunctions,omitempty"`
why did you feel this was necessary? I'd think the functions are always defined, if you don't need them don't use them...

2020-09-08 12:59 UTC, raffaelespazzoli commented on pkg/util/custom-funcmap.go
> +		"include":  func(string, interface{}) string { return "not implemented" },
please remove `include` and `tpl`.
please add the `lookup` function.
I'm on the edge for the `required` function, what do you think?

2020-09-08 16:26 UTC, cnuland commented on pkg/util/apis/locked-resource.go
> +	EnableAdvancedTemplateFunctions bool `json:"enableAdvancedTemplateFunctions,omitempty"`
Originally I was going to keep some of the functions that might pose a security risk, like the env functions, but since we have removed those completely then I don't see this being an issue having it default to false.

2020-09-08 16:32 UTC, raffaelespazzoli commented on pkg/util/custom-funcmap.go
> +func CustomFuncMap() template.FuncMap {
can we call this AdvancedTemplateFuncMap.
So the idea is that the operator developer has a choice of whether to initialize the templates with this func map.
I don't remember if we have utility functions to create the templates or if those are supposed to be written by the operator developer... If we do there should be an easy way to get a template initialized with this func map.

2020-09-08 16:52 UTC, cnuland commented on pkg/util/custom-funcmap.go
> +		"include":  func(string, interface{}) string { return "not implemented" },
I think we should also add `required`, I could see it being useful, especially with our project onboarding workstream for the operator. 

With that, I'd recommend that `include` and `required` be a separate issue/feature  PR. I personally like to keep my PR's small, it makes for easier debugging, management, and organization when working on a project like this one. This is my personal preference though, and I'm flexible if these functions are deal breakers for the PR. The reason I believe these two functions should be handled separately is because they both involve custom implementations, rather than just calling existing parsing methods like the existing ToYaml, ToJson, etc, as shown here for helm,

https://github.com/helm/helm/blob/master/pkg/engine/engine.go

2020-09-08 16:56 UTC, cnuland commented on pkg/util/custom-funcmap.go
> +func CustomFuncMap() template.FuncMap {
Right now the flag in the structs is the only deciding factor if the get the default `FuncMap` or this custom one. We do not have a way to pass in custom templates from the consuming operator of this library, if that is what you suggestion, but that is something I can make and I really like the concept. It would take some minor restructuring, but I don't see anything major inhibiting it. I would recommend this be a separate PR if that type of functionality is desired.

As for the name change, AdvancedTemplateFuncMap makes sense to me for the function name, I will make that change.

2020-09-08 17:57 UTC, raffaelespazzoli commented on pkg/util/custom-funcmap.go
> +		"include":  func(string, interface{}) string { return "not implemented" },
what do you mean by custom implementations? the implementations are in the helm code as for the `ToYaml` etc... functions.
Not sure I see the difference. We can copy and paste that code or even just import the helm package. Also I was the contributor of the lookup function, so I know that piece intimately. Not sure about where the required function is, but it has to be in the code....

2020-09-08 18:06 UTC, cnuland commented on pkg/util/custom-funcmap.go
> +		"include":  func(string, interface{}) string { return "not implemented" },
@raffaelespazzoli  sounds good, I have found both the `required` and the `lookup` implementations in the Helm code base now, let me go ahead and implement them.

2020-09-08 22:10 UTC, cnuland commented on README.md
> +- enableAdvancedTemplateFunctions: true
removed

2020-09-08 22:11 UTC, cnuland commented on README.md
> +  enableAdvancedTemplateFunctions: true
removed

2020-09-08 23:30 UTC, cnuland commented on pkg/util/custom-funcmap.go
> +		"include":  func(string, interface{}) string { return "not implemented" },
Added `lookup` and `required` 

```golang
  templates:
  - objectTemplate: |
      - apiVersion: v1
        kind: Namespace
        metadata:
          annotations:
            ncoCreatedOn: '{{ (lookup "v1" "Namespace" "" "namespace-configuration-operator").metadata.creationTimestamp }}'
            sourceTemplate: "{{ toYaml . | b64enc }}"
            require: '{{ required "Annotations on the Group are required!" .Annotations.test }}'
          name: {{ .Name | lower }}
```

2020-09-09 01:54 UTC, raffaelespazzoli requested changes
we need to refactor the documentation, the code looks good to me now.

2020-09-09 01:54 UTC, raffaelespazzoli commented on README.md
> +## Support for operators that need advanced templating functionality
we need to change the docs.
I'd just add a paragraph about support for advanced templating function. It should not refer specifically to locked resources , but to everywhere a template is being used, let's just say mention that if one wants advanced templating functions enabled they have to use that function that you defined to initialize the template engine.
Remember we are documenting the library template not the example operator.
Then let's add the list of function available or pointers to relative documentation.

2020-09-09 23:38 UTC, cnuland commented on README.md
> +## Support for operators that need advanced templating functionality
@raffaelespazzoli updated, I mention functionality that matches Helm's templating, curious if that is enough?

2020-09-10 00:53 UTC, raffaelespazzoli commented
LGTM

2020-09-10 00:53 UTC, merged