New patch
redhat-cop/operator-utils pull request #80
Opened 2021-12-09 02:25 UTC by raffaelespazzoli

2021-12-09 23:17 UTC, sabre1041 requested changes

2021-12-09 23:17 UTC, sabre1041 commented on README.md
> +Prior to version v2.x the general philosophy of this library was that new operator would inherint from REcorncileBase and in doing so they would havbe access to a bunch of utility methods.
```suggestion
Prior to version v2.x the general philosophy of this library was that new operator would inherent from ReconcileBase and in doing so they would have access to a bunch of utility methods.
```

2021-12-09 23:17 UTC, sabre1041 commented on README.md
> +With release v2.0.0 a new approach is avaibale. Utility methods are callable by any operator havintg to inehrit. This makes it easier to use this library and does not conflict with autogenerate code
```suggestion
With release v2.0.0, a new approach is available. Utility methods are callable by any operator having to inherit. This makes it easier to use this library and does not conflict with autogenerate code from `kube-builder` and `operator-sdk`.
```

2021-12-09 23:17 UTC, sabre1041 commented on README.md
> +Most of the Utility methods receive a context.Context parameter. Normally this context must be initialized with a `logr.Logger` and a `rest.Config`. Some utility methods may require more, see each in
```suggestion
Most of the Utility methods receive a `context.Context` parameter. Normally this context must be initialized with a `logr.Logger` and a `rest.Config`. Some utility methods may require more, see each individual documentation.
```

2021-12-09 23:17 UTC, sabre1041 commented on README.md
> +Utility methods are current organized in the following folders:
```suggestion
Utility methods are currently organized in the following folders:
```

2021-12-09 23:17 UTC, sabre1041 commented on README.md
> +2. discoveryclient: methods related to the discovery client, topically used to load `apiResource` objects.
```suggestion
2. discoveryclient: methods related to the discovery client, typically used to load `apiResource` objects.
```

2021-12-09 23:17 UTC, sabre1041 commented on pkg/util/reconciler.go
> +// // GetDynamicClientOnAPIResource returns a dynamic client on an APIResource. This client can be further namespaced.
Do we want to remove all of this commented out code?

2021-12-10 00:11 UTC, raffaelespazzoli commented on README.md
> +Prior to version v2.x the general philosophy of this library was that new operator would inherint from REcorncileBase and in doing so they would havbe access to a bunch of utility methods.
can you fix from inherent to inherit?

2021-12-10 00:12 UTC, raffaelespazzoli commented on README.md
> +With release v2.0.0 a new approach is avaibale. Utility methods are callable by any operator havintg to inehrit. This makes it easier to use this library and does not conflict with autogenerate code
can you change from `having` to `without having`?

2021-12-10 00:16 UTC, raffaelespazzoli commented on README.md
> +Prior to version v2.x the general philosophy of this library was that new operator would inherint from REcorncileBase and in doing so they would havbe access to a bunch of utility methods.
fixed

2021-12-10 00:16 UTC, raffaelespazzoli commented on README.md
> +With release v2.0.0 a new approach is avaibale. Utility methods are callable by any operator havintg to inehrit. This makes it easier to use this library and does not conflict with autogenerate code
fixed

2021-12-10 00:17 UTC, raffaelespazzoli commented on pkg/util/reconciler.go
> +// // GetDynamicClientOnAPIResource returns a dynamic client on an APIResource. This client can be further namespaced.
fixed

2021-12-10 00:21 UTC, raffaelespazzoli commented
all comments should have been addressed @sabre1041

2021-12-10 00:39 UTC, sabre1041 approved these changes
LGTM

2021-12-10 00:43 UTC, merged